"""Initial migration

Revision ID: df2a4ad13092
Revises: a91c2746ea85
Create Date: 2024-10-02 23:34:47.312661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df2a4ad13092'
down_revision: Union[str, None] = 'a91c2746ea85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
